circleci:
    # use user and password auth
    type: snowflake
    account: "rc56421.us-east-2"
    user: "{{ env_var('DBT_DATA_MODELING_SNOWFLAKE_USER', 'Deepak') }}"
    password: "{{ env_var('DBT_DATA_MODELING_SNOWFLAKE_PASSWORD', 'Deepu@822') }}"
    role: "{{ env_var('DBT_DATA_MODELING_SNOWFLAKE_ROLE', 'dbt_role') }}"
    database: "{{ env_var('DBT_DATA_MODELING_SNOWFLAKE_DATABASE', 'analytics') }}"
    warehouse: "dbt_wh"
    schema: "public"
    query_tag: "circleci_dbt"
