version: 2.1

jobs:
  dbt-cloud:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:          
          name: Setup Snowflake Connection
          command: |
            echo "SNOWSQL_ACCOUNT: $SNOWSQL_ACCOUNT"
            echo "SNOWSQL_USER: $SNOWSQL_USER"
            echo "SNOWSQL_PASSWORD: $SNOWSQL_PASSWORD"
      - run:
          name: Install dbt
          command: |
            pip install dbt
      - run:
          name: "Run dbt commands"
          command: |
            echo "Buid success"
      - run:
          name: "Pipeline builded"
          command: echo "Snowflake succeeded!"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - dbt-cloud
